src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'Offre_Type',type: 'string')]
#[ORM\DiscriminatorMap(["Offre"=>Offre::class,"Internship"=>InternShip::class,"Job"=>Job::class])]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Limit_Date = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Req_Skills = null;

    public function getReqSkills(): ?string
    {
        return $this->Req_Skills;
    }

    public function setReqSkills(?string $Req_Skills): void
    {
        $this->Req_Skills = $Req_Skills;
    }

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Mission = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\ManyToMany(targetEntity: Candidat::class, mappedBy: 'Offre')]
    private Collection $candidats;

    #[ORM\ManyToOne(inversedBy: 'Offre')]
    private ?Recruiter $recruiter = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $TimeType = null;

    public function __construct()
    {
        $this->candidats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): static
    {
        $this->Title = $Title;

        return $this;
    }

    public function getLimitDate(): ?\DateTimeInterface
    {
        return $this->Limit_Date;
    }

    public function setLimitDate(?\DateTimeInterface $Limit_Date): static
    {
        $this->Limit_Date = $Limit_Date;

        return $this;
    }



    public function getMission(): ?string
    {
        return $this->Mission;
    }

    public function setMission(?string $Mission): static
    {
        $this->Mission = $Mission;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Candidat>
     */
    public function getCandidats(): Collection
    {
        return $this->candidats;
    }

    public function addCandidat(Candidat $candidat): static
    {
        if (!$this->candidats->contains($candidat)) {
            $this->candidats->add($candidat);
            $candidat->addOffre($this);
        }

        return $this;
    }

    public function removeCandidat(Candidat $candidat): static
    {
        if ($this->candidats->removeElement($candidat)) {
            $candidat->removeOffre($this);
        }

        return $this;
    }

    public function getRecruiter(): ?Recruiter
    {
        return $this->recruiter;
    }

    public function setRecruiter(?Recruiter $recruiter): static
    {
        $this->recruiter = $recruiter;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(?string $Location): static
    {
        $this->Location = $Location;

        return $this;
    }

    public function getTimeType(): ?string
    {
        return $this->TimeType;
    }

    public function setTimeType(?string $TimeType): static
    {
        $this->TimeType = $TimeType;

        return $this;
    }
}

src/Controller/HomeRecruteurController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Entity\Offre;
use App\Form\JobType;
use App\Form\RecruiterUpdateType;
use App\Repository\InternShipRepository;
use App\Repository\JobRepository;
use App\Repository\OffreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


#[Route('/dashboard')]
class HomeRecruteurController extends AbstractController
{
    #[Route('/', name: 'app_home_recruteur')]
    public function index(JobRepository $jobRepository,OffreRepository $offreRepository,InternShipRepository $internShipRepository): Response
    {
        $recruiter = $this->getUser();
        $recruiterId = $recruiter->getId();
        $totalOffres = $offreRepository->count(['recruiter' => $recruiterId]);
        $totalJobs = $jobRepository->count(['recruiter' => $recruiterId]);
        $totalInternships = $internShipRepository->count(['recruiter' => $recruiterId]);
        $totalSubmitedOffers = $offreRepository->countOffers($recruiterId);
        return $this->render('home_recruteur/index.html.twig', [
            'controller_name' => 'HomeRecruteurController',
            'totalJobs' => $totalJobs,
            'totalOffres'=>$totalOffres,
            'totalInternShips'=>$totalInternships,
            'totalSubOffers'=>$totalSubmitedOffers
        ]);
    }


    #[Route('/appliedJobs',name: 'applied_jobs')]
    public function appliedJobs(OffreRepository $offreRepository): Response
    {
        $recruiter = $this->getUser();
        $recruiterId = $recruiter->getId();
        $offersWithCandidates = $offreRepository->findOffreCandidatIds($recruiterId);
        return $this->render('home_recruteur/appliedjobs.html.twig',[
            'offersWithCandidates'=>$offersWithCandidates,
        ]);
    }

    #[Route ('/alljobs',name:'get_all_jobs',methods: ['GET'])]
    public function allJobs(OffreRepository $offreRepository): Response
    {
        $recruiter = $this->getUser();
        return $this->render('home_recruteur/tables.html.twig', [
            'offers' => $offreRepository->findBy(['recruiter'=>$recruiter]),
        ]);
    }
    #[Route ('/edit/profile',name:'edit_profile_rec',methods: ['GET','POST'])]
        public function editRecruiter(Request $request,EntityManagerInterface $em):Response{
            $recruiter=$this->getUser();
            $form=$this->createForm(RecruiterUpdateType::class,$recruiter);
            $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            return $this->redirectToRoute('app_home_recruteur');
        }

        return $this->render('home_recruteur/updateprofile.html.twig', [
            'form' => $form->createView(),
        ]);
        }

}

templates/home_recruteur/addInternship.html.twig
<!DOCTYPE html>
<html lang="en">

{% include '/home_recruteur/head.html.twig' %}

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <!-- Topbar -->
            {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">

                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{% include '/home_recruteur/logoutModal.html.twig' %}

<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/assets/js/demo/datatables-demo.js"></script>

</body>

</html>

templates/home_recruteur/addJob.html.twig
<!DOCTYPE html>
<html lang="en">


    {% include '/home_recruteur/head.html.twig' %}


<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <!-- Topbar -->
            {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">

                {{ form_start(form) }}

                {{ form_row(form.Title) }}
                {{ form_row(form.Limit_Date) }}
                {{ form_row(form.Mission) }}
                {{ form_row(form.Description) }}
                {{ form_row(form.Req_Skills) }}
                {{ form_row(form.Salary_Prop) }}
                {{ form_row(form.Contract_Type) }}
                {{ form_row(form.TimeType) }}
                {{ form_row(form.Location) }}
                <button class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


<!-- Logout Modal-->
{% include '/home_recruteur/logoutModal.html.twig' %}

<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/assets/js/demo/datatables-demo.js"></script>

</body>

</html>

templates/home_recruteur/appliedjobs.html.twig
<!DOCTYPE html>
<html lang="en">

{% include '/home_recruteur/head.html.twig' %}

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <!-- Topbar -->
            {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">




                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Jobs List</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Offre ID</th>
                                    <th>Offre Title </th>
                                    <th>Candidat Full Name</th>
                                    <th>Candidat Email</th>
                                    <th> Download Cv </th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for row in offersWithCandidates %}


                                <tr>
                                    <td>{{ row.offre_id }}</td>
                                    <td>{{ row.offre_title }}</td>
                                    <td>{{ row.candidat_name}} {{ row.candidat_lastname }}</td>
                                    <td> {{ row.candidat_email}} </td>
                                    <td> <a href="{{ asset('assets/files/' ~ row.candidat_cv) }}" download> <i class="fa fa-download" style="text-align: center"> </i> </a> </td>
                                </tr>
                                </tbody>
                                {% else %}
                                    <tr>
                                        <td colspan="9">no Applied Jobs found</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{% include '/home_recruteur/logoutModal.html.twig' %}

<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/assets/js/demo/datatables-demo.js"></script>

</body>

</html>

templates/home_recruteur/editJob.html.twig
<!DOCTYPE html>
<html lang="en">


    {% include '/home_recruteur/head.html.twig' %}


<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <!-- Topbar -->
            {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">

                {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>
                {{ form_end(form) }}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{% include '/home_recruteur/logoutModal.html.twig' %}

<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/assets/js/demo/datatables-demo.js"></script>

</body>

</html>

templates/home_recruteur/index.html.twig
<html lang="en">

{% include '/home_recruteur/head.html.twig' %}

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
        {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">



                <!-- Content Row -->
                <div class="row">

                    <!-- Earnings (Monthly) Card Example -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                           Total Offers</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ totalOffres }}</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Earnings (Monthly) Card Example -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-success shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                            Total Jobs </div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ totalJobs }}</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- Earnings (Monthly) Card Example -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-success shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                            Total Internships </div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ totalInternShips }} </div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-success shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                            Total Submited Offer </div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ totalSubOffers }} </div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Pending Requests Card Example -->

                </div>
            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
                {% include '/home_recruteur/logoutModal.html.twig' %}

        <!-- Bootstrap core JavaScript-->
        <script src="/assets/vendor/jquery/jquery.min.js"></script>
        <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="/assets/js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="/assets/vendor/chart.js/Chart.min.js"></script>

        <!-- Page level custom scripts -->
        <script src="/assets/js/demo/chart-area-demo.js"></script>
        <script src="/assets/js/demo/chart-pie-demo.js"></script>

</body>

</html>

templates/home_recruteur/sidebar.html.twig
{% block content %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{path('app_home_recruteur')}}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-database"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Dashboard  </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{path('app_home_recruteur')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>



    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">

        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>


    <li class="nav-item">
        <a class="nav-link" href="{{ path('app_job_new') }}">
            <i class="fas fa-fw fa-briefcase"></i>
            <span>Add a new Job Offer </span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ path('app_intern_ship_new') }}">
            <i class="fas fa-fw fa-book-reader"></i>
            <span>Add a new Internship Offer </span></a>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <li class="nav-item">
        <a class="nav-link" href="{{ path('get_all_jobs') }}">
            <i class="fas fa-fw fa-table"></i>
            <span>List of Jobs </span></a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ path('applied_jobs') }}">
            <i class="fas fa-fw fa-table"></i>
            <span> Applied Offers </span></a>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <li class="nav-item">
        <a class="nav-link" href="{{ path('app_logout') }}">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            <span>Logout </span>
        </a>
    </li>

</ul>

{% endblock %}

templates/home_recruteur/tables.html.twig
<!DOCTYPE html>
<html lang="en">

{% include '/home_recruteur/head.html.twig' %}

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include '/home_recruteur/sidebar.html.twig' %}
    <!-- End of Sidebar -->


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <!-- Topbar -->
            {% include '/home_recruteur/topBar.html.twig' %}
            <!-- End of Topbar -->


            <!-- Begin Page Content -->
            <div class="container-fluid">




                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Jobs List</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Limit Date</th>
{#                                    <th>Type</th>#}
                                    <th>Mission</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for offre in offers %}
                                <tr>
                                    <td>{{ offre.Title }}</td>
                                    <td>{{ offre.LimitDate ? offre.LimitDate|date('Y-m-d') : '' }}</td>
{#                                    <td>{{ offre.discriminatorValue }}</td>#}
                                    <td>{{ offre.mission }}</td>
                                    <td><a href="{{ path('app_job_edit',{'id':offre.id}) }}"> <button class="btn"> <i class="fa fa-edit" style="color: lightblue;"></i>  </button> </a> </td>

                                    <td> <form method="post" action="{{ path('app_offre_delete', {'id': offre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this offre?');">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offre.id) }}">
                                           <button class="btn"> <i class="fa fa-trash" style="color: lightcoral;"> </i> </button>
                                        </form> </td>
                                </tr>
                                </tbody>
                                {% else %}
                                    <tr>
                                        <td colspan="9">no Jobs found</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->


    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
{% include '/home_recruteur/logoutModal.html.twig' %}

<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/assets/js/demo/datatables-demo.js"></script>

</body>

</html>