src/Entity/InternShip.php
<?php

namespace App\Entity;

use App\Repository\InternShipRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InternShipRepository::class)]
class InternShip extends Offre
{
    #[ORM\Column]
    private ?string $Payed = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Start_Date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    public function isPayed(): ?bool
    {
        return $this->Payed;
    }

    public function setPayed(bool $Payed): static
    {
        $this->Payed = $Payed;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->Start_Date;
    }

    public function setStartDate(\DateTimeInterface $Start_Date): static
    {
        $this->Start_Date = $Start_Date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }
}

src/Form/InternShipType.php
<?php

namespace App\Form;

use App\Entity\InternShip;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InternShipType extends OffreType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        parent::buildForm($builder,$options);
        $builder

            ->add('Payed',ChoiceType::class,[
                'choices'=>[
                    'YES'=>true,
                    'NO'=>false
            ],
                'expanded'=>true,
            ])
            ->add('Start_Date',DateType::class)
            ->add('end_date',DateType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => InternShip::class,
        ]);
    }
}

src/Controller/InternShipController.php
<?php

namespace App\Controller;

use App\Entity\InternShip;
use App\Form\InternShipType;
use App\Repository\InternShipRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/internship')]
class InternShipController extends AbstractController
{
    #[Route('/', name: 'app_intern_ship_index', methods: ['GET'])]
    public function index(InternShipRepository $internShipRepository): Response
    {
        return $this->render('internship/index.html.twig', [
            'internships' => $internShipRepository->findAll(),
        ]);
    }

    #[Route('/newIntership', name: 'app_intern_ship_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $internShip = new InternShip();
        $form = $this->createForm(InternShipType::class, $internShip);
        $form->handleRequest($request);
        $recruiter = $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($internShip);
            $internShip->setRecruiter($recruiter);
            $entityManager->flush();

            return $this->redirectToRoute('get_all_jobs', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('/home_recruteur/addInternship.html.twig', [
            'internShip' => $internShip,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_intern_ship_show', methods: ['GET'])]
    public function show(InternShip $internShip): Response
    {
        return $this->render('internship/show.html.twig', [
            'internShip' => $internShip,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_intern_ship_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, InternShip $internShip, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InternShipType::class, $internShip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_intern_ship_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('intern_ship/edit.html.twig', [
            'intern_ship' => $internShip,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_intern_ship_delete', methods: ['POST'])]
    public function delete(Request $request, InternShip $internShip, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$internShip->getId(), $request->request->get('_token'))) {
            $entityManager->remove($internShip);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_intern_ship_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/internship/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Intership Offers{% endblock %}

{% block body %}


    <!-- Jobs Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Internship Offers</h1>
            <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">

                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        {% for internhip in internships %}
                        <div class="job-item p-4 mb-4">

                            <div class="row g-4">
                                <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                    <img class="flex-shrink-0 img-fluid border rounded" src="/assets/img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">

                                    <div class="text-start ps-4">
                                        <h5 class="mb-3"> <a href="{{ path('app_intern_ship_show', { 'id': internhip.id }) }}" > {{ internhip.Title }} </a> </h5>
                                        <span class="text-truncate me-3"><i class="fa fa-map-marked-alt text-primary me-2"> </i>  <b> Location : </b> {{ internhip.Location }}</span>
                                        <span class="text-truncate me-3"><i class="far fa-calendar-alt text-primary me-2"> </i> <b> Limit Date : </b> {{ internhip.LimitDate ? internhip.LimitDate|date('Y-m-d') : '' }}</span>
                                    </div>



                                </div>
                                <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                    <div class="d-flex mb-3">
                                        <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                        <div class="d-flex mb-3">
                                            {% if app.user %}
                                                <a class="btn btn-primary" href="{{ path('apply_to_job', { 'id': internhip.id }) }}">Apply Now</a>
                                            {% else  %}
                                                <a class="btn btn-primary" href="{{ path('app_login') }}">Connect to aplly </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    {% else %}
                        <tr>
                            <td colspan="9">no Jobs found</td>
                        </tr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Jobs End -->


{% endblock %}

templates/internship/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Job{% endblock %}

{% block body %}
<div class="container-xxl py-5 bg-dark page-header mb-5">
    <div class="container my-5 pt-5 pb-4">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ internShip.Title }} Detail </h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb text-uppercase">
                <li class="breadcrumb-item"><a href="{{ path ('app_home_page') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ path('app_job_index') }}">Job Offers</a></li>
                <li class="breadcrumb-item text-white active" aria-current="page">{{ internShip.Title }}</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Header End -->
<!-- Job Detail Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="row gy-5 gx-4">
            <div class="col-lg-8">
                <div class="d-flex align-items-center mb-5">
                    <img class="flex-shrink-0 img-fluid border rounded" src="/assets/img/com-logo-2.jpg" alt="" style="width: 80px; height: 80px;">
                    <div class="text-start ps-4">
                        <h3 class="mb-3">{{ internShip.Title }}</h3>
                        <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ internShip.Location }}</span>
                        {% if internShip.payed == 1 %}
                        <span class="text-truncate me-3"><i class="far fa-money-bill-alt text-primary me-2"> </i> Payed Internship
                        </span>
                        {% else %}
                        <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"> </i>Not Payed Internship </span>
                        {% endif %}

                        <span class="text-truncate me-0"><i class="far fa-calendar-check text-primary me-2"></i>  <b> From : </b> {{ internShip.startDate ? internShip.startDate|date('Y-m-d') : ''}} <b>  To : </b> {{ internShip.startDate ? internShip.endDate|date('Y-m-d') : ''}}</span>
                    </div>
                </div>

                <div class="mb-5">
                    <h4 class="mb-3">Internship description</h4>
                    <p>{{ internShip.Description }}</p>
                    <h4 class="mb-3">Responsibility</h4>
                    <p>{{ internShip.Mission }}</p>
                    <h4 class="mb-3">Required Skills </h4>
                    <p>{{ internShip.ReqSkills ? internShip.ReqSkills|join(', ') : '' }}</p>


                </div>

            </div>
        </div>
    </div>

    <!-- Job Detail End -->
    <div class="d-flex mb-3">
        {% if app.user %}
            <a class="btn btn-outline-primary btn-lg" href="{{ path('apply_to_job', { 'id': internShip.id }) }}">Apply Now</a>
        {% else  %}
            <a class="btn btn-primary btn-lg" href="{{ path('app_login') }}">Connect to aplly </a>
        {% endif %}
    </div>
</div>
    {% endblock %}